apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karpenter

resources:
  - ec2-node-class.yaml
  - node-pool.yaml

commonLabels:
  app: karpenter
  managed-by: argocd

commonAnnotations:
  managed-by: karpenter
